# Generated by Django 2.1.5 on 2022-09-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220927_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete='auth.User', related_name='author', to='home.BlogModel'),
        ),
    ]
