# Generated by Django 2.1.5 on 2022-09-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220927_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='choice_text',
        ),
    ]
